### ISSUE TITLE
Interested in Partnering?

### ISSUE THREAD

**Issue by ctalkington** [lvcabral/ha-roku-cast-app#1]
Roku recently axed PlayOnRoku for third parties in OS 11.5.

Are you interested in working with me and taking this solution you created to Roku Store as a public channel? Assuming we can get it past requirement.

I would then make it the preferred channel in rokuecp and HA integration.

**Comment by lvcabral** [comment]
Hi Chris, let's talk on private, e-mail me at `marcelo dot cabral at google e-mail domain`

**Comment by carefulcomputer** [comment]
any updates ?

**Comment by alex4108** [comment]
meep
